### ISSUE TITLE
Error in uploading file to installed Jupiter notebook.

### ISSUE THREAD

**Issue by zed-creator** [mholtrop/QMPython#1]
Hi,
While using Anaconda 3 and Jupiter notebook, tried to upload all 3 .jpynb files in a folder, but the following error occurs-
The error was: SyntaxError: Unexpected token < in JSON at position 6
Using Python 3.9.1.
Thanks.

**Comment by mholtrop** [comment]
These are .ipynb not .jpynb files. You need to open these files _inside a Jupyter notebook_, you do not open them in Python.
